### ISSUE TITLE
Code for Fig. 3: Joint distribution of two axes

### ISSUE THREAD

**Issue by houjunlin** [zhiCHEN96/ConceptWhitening#17]
Hi everyone!
Thanks for sharing the code. I would like to visualize the joint distribution of two axes as shown in Fig. 3. Any code in the plot_functions.py file may I use to achieve this? Many thanks!

Best,
JL

**Comment by zhiCHEN96** [comment]
Hi Junlin,

You can use the plot_concept_representation function (line 892) in plot_functions.py

Best,
Zhi

**Comment by houjunlin** [comment]
Hi Zhi,
Thanks for your reply! I have run it successfully.
