### ISSUE TITLE
Regarding the concept datasets

### ISSUE THREAD

**Issue by sakura7621** [zhiCHEN96/ConceptWhitening#2]
Hi,

I have some problems with the concept datasets while trying to re-train the model.
The data from *MS COCO* (https://cocodataset.org) contains images that need to be pre-processed (e.g., *cropped*) before feeding into the model.
Can you please provide the concept datasets?

Thank you!

**Comment by zhiCHEN96** [comment]
Hi,

We just upload the preprocessing code for the COCO dataset. Please check cropping_images_COCO.py.
