### ISSUE TITLE
Illegal instruction

### ISSUE THREAD

**Issue by fangzhouli** [zhiCHEN96/ConceptWhitening#7]
Hi,

Thank you for reading. I am trying to run the module, with both CLI and shell script, but it always show "Illegal instruction". I guess it's versioning issue.

I'm using python 3.6, and all packages with correct versions. Please let me know if you need more info to identify the issue!

Thanks,
Fang

**Comment by zhiCHEN96** [comment]
Hi Fang,

Sorry for late reply. I notice that you just closed the issue. Did you fix the problem? If so, what was the cause of this problem and how did you fix it?

**Comment by fangzhouli** [comment]
Hi Zhi,

Thanks! It was a stupid mistake that my GPU dependency was misconfigures on
our Slurm system. Thank you for the help tho!

Best,
Fang
