### ISSUE TITLE
Difficulty replicating the test results

### ISSUE THREAD

**Issue by fangzhouli** [zhiCHEN96/ConceptWhitening#9]
Hi Zhi, thank you for reading. I am trying to replicate or at least run the train/test to see the results. Currently I have meeting difficulties even though I am following the instruction. 

Here is what I did :
(1) Since Places365 test is not labelled, I am using validation set (not used in training).
(2) I ran your train_places_resnet18_concept_whitening_transfer.sh, and used the adjusted test script accordingly.
(3) Pretrained on the default resnet18 with 1 epoch, top5 ~83.

I have done minimal adjustment to your plot_concept_top50's data loader to work for val_loader, which is the only change I did. The resulting top 50 images are very random, no related concepts. Let me know if you need additional info.

**Comment by zhiCHEN96** [comment]
That's weird. Are you using the same concepts and same whitened layer in both train and test scripts?

**Comment by fangzhouli** [comment]
Yes, I believe so. The way how checkpoints are named should prevent me accidentally input different layer/concepts.

Here are my train and test scripts:

- train.sh:
python ../train_places.py /path/to/my/ConceptWhitening/data_256/ \
    --ngpu 1 \
    --workers 32 \
    --arch resnet_cw \
    --depth 18 \
    --epochs 200 \
    --batch-size 64 \
    --lr 0.05 \
    --whitened_layers 7 \
    --concepts bicycle,bird,boat,cat,chair,knife,microwave,pizza,skis \
    --prefix RESNET18_PLACES365_CPT_WHITEN_TRANSFER

- test.sh:
python ../train_places.py /path/to/my/ConceptWhitening/data_256/ \
    --seed 1232 \
    --ngpu 1 \
    --workers 64 \
    --arch resnet_cw \
    --depth 18 \
    --epochs 200 \
    --batch-size 1 \
    --lr 0.1 \
    --whitened_layers 7 \
    --concepts bicycle,bird,boat,cat,chair,knife,microwave,pizza,skis \
    --prefix RESNET18_PLACES365_CPT_WHITEN_TRANSFER \
    --resume ./checkpoints/RESNET18_PLACES365_CPT_WHITEN_TRANSFER_model_best.pth.tar \
    --evaluate

Hope it helps,
Fang

**Comment by zhiCHEN96** [comment]
There's also a _whitened_layers_ parameter in the function _plot_concept_top50_, see
def plot_concept_top50(args, val_loader, model, whitened_layers, print_other = False, activation_mode = 'pool_max'):

Also, for debugging purpose, would you also try airplane,bed,bench,boat,book,horse,person as the concept and whitened_layers=8? That's the setting used in the paper.

**Comment by fangzhouli** [comment]
Yes, all the plot functions are also using whitened_layer='7'

I will try the concepts you mentioned and report to you later.

Thanks!

**Comment by zhiCHEN96** [comment]
Hi Fang,

I reran the model using your settings (although I'm using workers=4 in training and workers=1 and batch_size=64 in testing, but they shouldn't affect the results).

The resulting top 50 images are NOT random. For example, "pizza" contains mostly pizza and "skies" contains mostly skiing people (also contains few snow mountain pictures). Some concepts are less pure, but still contains certain abstraction of target concepts. "Bicycle" contains some bicycles and some circular metal stuff. "Bird" contains some birds and some animals in the wild. This makes sense because whitened_layer='7', which is not the final layer, and the network would learn different concepts in different layers --- some concepts like "bird" are not fully learned until the last layer. In fact, this is an example of how CW can help discover how concepts are gradually learned in a neural network.

To avoid confusion like this, I'll change the training script so that it matches with the concepts in the testing script.

**Comment by fangzhouli** [comment]
Hi Zhi,

Thank you. Just to confirm, are you using places365's validation set while plotting, or a split of original training set while plotting?

I am using validation set for plotting.

**Comment by zhiCHEN96** [comment]
I'm also using the original validation set of places365.

**Comment by expectopatronum** [comment]
I try to run exactly the same and the train.sh finished successfully, however I can't run the test code. It crashes with the following error:

`FileNotFoundError: [Errno 2] No such file or directory: '/my/project/path/plots/airplane_bed_bench_boat_book_horse_person/resnet_cw18/1_rot_cw_top5'`

I looked a bit closer into the code and I noticed that the function `plot_concept_top50` is commented out [here](https://github.com/zhiCHEN96/ConceptWhitening/blob/a369fb4334cca59f2cc97b72a33df6b9a9903bd8/train_places.py#L476).

Should I just uncomment the parts corresponding to the layer I am looking at, e.g. this part?

```
    # model = load_resnet_model(args, arch = 'resnet_cw', depth=18, whitened_layer='8')
    # plot_concept_top50(args, test_loader_with_path, model, '8', activation_mode = args.act_mode)
```

**Comment by zhiCHEN96** [comment]
> I try to run exactly the same and the train.sh finished successfully, however I can't run the test code. It crashes with the following error:
> 
> I looked a bit closer into the code and I noticed that the function `plot_concept_top50` is commented out [here](https://github.com/zhiCHEN96/ConceptWhitening/blob/a369fb4334cca59f2cc97b72a33df6b9a9903bd8/train_places.py#L476).
> 
> Should I just uncomment the parts corresponding to the layer I am looking at, e.g. this part?
> 
> ```
>     # model = load_resnet_model(args, arch = 'resnet_cw', depth=18, whitened_layer='8')
>     # plot_concept_top50(args, test_loader_with_path, model, '8', activation_mode = args.act_mode)
> ```

Yes, also you should make sure the whitened layer is the same as the layer you trained for CW.

**Comment by expectopatronum** [comment]
@fangzhouli 

> I have done minimal adjustment to your plot_concept_top50's data loader to work for val_loader, which is the only change I did. The resulting top 50 images are very random, no related concepts. Let me know if you need additional info.

what changes did you make to plot_concept_top50's data loader? I uncommented several lines that seem related to plotting, but I still can't get it to work. your help would be really appreciated, thanks!

**Comment by zhiCHEN96** [comment]
> @fangzhouli
> 
> > I have done minimal adjustment to your plot_concept_top50's data loader to work for val_loader, which is the only change I did. The resulting top 50 images are very random, no related concepts. Let me know if you need additional info.
> 
> what changes did you make to plot_concept_top50's data loader? I uncommented several lines that seem related to plotting, but I still can't get it to work. your help would be really appreciated, thanks!

Hi, would you uncomment line 251 and comment line 252, and comment the val_loader_2 stuff (line 165-173). val_loader_2 is actually not used in plotting the top 50 images. Sorry for the confusion.

**Comment by fangzhouli** [comment]
Hi Zhi, sorry for a late response. The code works now! Using the ImageFolderWithPaths did the trick! Thank you for all the help!
